# Generated by Django 6.0.4 on 2026-04-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_remove_expense_date_remove_trip_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
